package model;
// Generated Feb 28, 2018 5:28:46 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Barang generated by hbm2java
 */
public class Barang  implements java.io.Serializable {


     private Integer idBarang;
     private String namaBarang;
     private String hargaBarang;
     private Set<Wishlistentry> wishlistentries = new HashSet<Wishlistentry>(0);
     private Set<Etalase> etalases = new HashSet<Etalase>(0);
     private Set<Shoppingcartentry> shoppingcartentries = new HashSet<Shoppingcartentry>(0);
     private Set<Kategori> kategoris = new HashSet<Kategori>(0);
     private Set<Orderentry> orderentries = new HashSet<Orderentry>(0);

    public Barang() {
    }

	
    public Barang(String namaBarang, String hargaBarang) {
        this.namaBarang = namaBarang;
        this.hargaBarang = hargaBarang;
    }
    public Barang(String namaBarang, String hargaBarang, Set<Wishlistentry> wishlistentries, Set<Etalase> etalases, Set<Shoppingcartentry> shoppingcartentries, Set<Kategori> kategoris, Set<Orderentry> orderentries) {
       this.namaBarang = namaBarang;
       this.hargaBarang = hargaBarang;
       this.wishlistentries = wishlistentries;
       this.etalases = etalases;
       this.shoppingcartentries = shoppingcartentries;
       this.kategoris = kategoris;
       this.orderentries = orderentries;
    }
   
    public Integer getIdBarang() {
        return this.idBarang;
    }
    
    public void setIdBarang(Integer idBarang) {
        this.idBarang = idBarang;
    }
    public String getNamaBarang() {
        return this.namaBarang;
    }
    
    public void setNamaBarang(String namaBarang) {
        this.namaBarang = namaBarang;
    }
    public String getHargaBarang() {
        return this.hargaBarang;
    }
    
    public void setHargaBarang(String hargaBarang) {
        this.hargaBarang = hargaBarang;
    }
    public Set<Wishlistentry> getWishlistentries() {
        return this.wishlistentries;
    }
    
    public void setWishlistentries(Set<Wishlistentry> wishlistentries) {
        this.wishlistentries = wishlistentries;
    }
    public Set<Etalase> getEtalases() {
        return this.etalases;
    }
    
    public void setEtalases(Set<Etalase> etalases) {
        this.etalases = etalases;
    }
    public Set<Shoppingcartentry> getShoppingcartentries() {
        return this.shoppingcartentries;
    }
    
    public void setShoppingcartentries(Set<Shoppingcartentry> shoppingcartentries) {
        this.shoppingcartentries = shoppingcartentries;
    }
    public Set<Kategori> getKategoris() {
        return this.kategoris;
    }
    
    public void setKategoris(Set<Kategori> kategoris) {
        this.kategoris = kategoris;
    }
    public Set<Orderentry> getOrderentries() {
        return this.orderentries;
    }
    
    public void setOrderentries(Set<Orderentry> orderentries) {
        this.orderentries = orderentries;
    }




}


