package model;
// Generated Mar 7, 2018 11:31:33 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;

/**
 * Barang generated by hbm2java
 */
public class Barang  implements java.io.Serializable {
   

     private Integer idBarang;
     private String namaBarang;
     private int hargaBarang;
     private Set<Wishlistentry> wishlistentries = new HashSet<Wishlistentry>(0);
     private Set<Etalase> etalases = new HashSet<Etalase>(0);
     private Set<Shoppingcartentry> shoppingcartentries = new HashSet<Shoppingcartentry>(0);
    @ManyToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY)
    @JoinTable(name = "kategoribarang",catalog = "gulungtikar",
    joinColumns = @JoinColumn(name = "ID_barang", referencedColumnName = "ID_barang"),
    inverseJoinColumns = @JoinColumn(name = "ID_kategori", referencedColumnName = "ID_kategori"))
     private Set<Kategori> kategoris = new HashSet<Kategori>(0);
     private Set<Orderentry> orderentries = new HashSet<Orderentry>(0);

    public Barang() {
    }

	
    public Barang(String namaBarang, int hargaBarang) {
        this.namaBarang = namaBarang;
        this.hargaBarang = hargaBarang;
    }
    public Barang(String namaBarang, int hargaBarang, Set<Wishlistentry> wishlistentries, Set<Etalase> etalases, Set<Shoppingcartentry> shoppingcartentries, Set<Kategori> kategoris, Set<Orderentry> orderentries) {
       this.namaBarang = namaBarang;
       this.hargaBarang = hargaBarang;
       this.wishlistentries = wishlistentries;
       this.etalases = etalases;
       this.shoppingcartentries = shoppingcartentries;
       this.kategoris = kategoris;
       this.orderentries = orderentries;
    }
   
    public Integer getIdBarang() {
        return this.idBarang;
    }
    
    public void setIdBarang(Integer idBarang) {
        this.idBarang = idBarang;
    }
    public String getNamaBarang() {
        return this.namaBarang;
    }
    
    public void setNamaBarang(String namaBarang) {
        this.namaBarang = namaBarang;
    }
    public int getHargaBarang() {
        return this.hargaBarang;
    }
    
    public void setHargaBarang(int hargaBarang) {
        this.hargaBarang = hargaBarang;
    }
    public Set<Wishlistentry> getWishlistentries() {
        return this.wishlistentries;
    }
    
    public void setWishlistentries(Set<Wishlistentry> wishlistentries) {
        this.wishlistentries = wishlistentries;
    }
    public Set<Etalase> getEtalases() {
        return this.etalases;
    }
    
    public void setEtalases(Set<Etalase> etalases) {
        this.etalases = etalases;
    }
    public Set<Shoppingcartentry> getShoppingcartentries() {
        return this.shoppingcartentries;
    }
    
    public void setShoppingcartentries(Set<Shoppingcartentry> shoppingcartentries) {
        this.shoppingcartentries = shoppingcartentries;
    }
    
   
    public Set<Kategori> getKategoris() {
        return this.kategoris;
    }
     
   
    public void setKategoris(Set<Kategori> kategoris) {
        this.kategoris = kategoris;
    }
    public Set<Orderentry> getOrderentries() {
        return this.orderentries;
    }
    
    public void setOrderentries(Set<Orderentry> orderentries) {
        this.orderentries = orderentries;
    }




}


