package model;
// Generated Mar 7, 2018 11:31:33 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;

/**
 * Kategori generated by hbm2java
 */
public class Kategori  implements java.io.Serializable {
    

     private int idKategori;
     private String namaKategori;
    @ManyToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY)
    @JoinTable(name = "kategoribarang",catalog = "gulungtikar",
    joinColumns = @JoinColumn(name = "ID_kategori", referencedColumnName = "ID_kategori"),
    inverseJoinColumns = @JoinColumn(name = "ID_barang", referencedColumnName = "ID_barang"))
     private Set<Barang> barangs = new HashSet<Barang>(0);

    public Kategori() {
    }

	
    public Kategori(int idKategori) {
        this.idKategori = idKategori;
    }
    public Kategori(int idKategori, String namaKategori, Set<Barang> barangs) {
       this.idKategori = idKategori;
       this.namaKategori = namaKategori;
       this.barangs = barangs;
    }
   
    public int getIdKategori() {
        return this.idKategori;
    }
    
    public void setIdKategori(int idKategori) {
        this.idKategori = idKategori;
    }
    public String getNamaKategori() {
        return this.namaKategori;
    }
    
    public void setNamaKategori(String namaKategori) {
        this.namaKategori = namaKategori;
    }
   
    public Set<Barang> getBarangs() {
        return this.barangs;
    }
   
    public void setBarangs(Set<Barang> barangs) {
        this.barangs = barangs;
    }




}


