package model;
// Generated Feb 28, 2018 5:28:46 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Kategori generated by hbm2java
 */
public class Kategori  implements java.io.Serializable {


     private int idKategori;
     private String namaKategori;
     private Set<Barang> barangs = new HashSet<Barang>(0);

    public Kategori() {
    }

	
    public Kategori(int idKategori) {
        this.idKategori = idKategori;
    }
    public Kategori(int idKategori, String namaKategori, Set<Barang> barangs) {
       this.idKategori = idKategori;
       this.namaKategori = namaKategori;
       this.barangs = barangs;
    }
   
    public int getIdKategori() {
        return this.idKategori;
    }
    
    public void setIdKategori(int idKategori) {
        this.idKategori = idKategori;
    }
    public String getNamaKategori() {
        return this.namaKategori;
    }
    
    public void setNamaKategori(String namaKategori) {
        this.namaKategori = namaKategori;
    }
    public Set<Barang> getBarangs() {
        return this.barangs;
    }
    
    public void setBarangs(Set<Barang> barangs) {
        this.barangs = barangs;
    }




}


