package model;
// Generated Mar 7, 2018 11:31:33 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Pengguna generated by hbm2java
 */
public class Pengguna  implements java.io.Serializable {


     private Integer idPengguna;
     private String password;
     private String email;
     private String nama;
     private String alamatRumah;
     private String type;
     private String noRekening;
     private int saldo;
     private Set<Toko> tokos = new HashSet<Toko>(0);
     private Set<Shoppingcart> shoppingcarts = new HashSet<Shoppingcart>(0);
     private Set<Transaksi> transaksis = new HashSet<Transaksi>(0);
     private Set<Wishlist> wishlists = new HashSet<Wishlist>(0);

    public Pengguna() {
    }

	
    public Pengguna(String password, String email, String nama, String alamatRumah, String type, String noRekening, int saldo) {
        this.password = password;
        this.email = email;
        this.nama = nama;
        this.alamatRumah = alamatRumah;
        this.type = type;
        this.noRekening = noRekening;
        this.saldo = saldo;
    }
    public Pengguna(String password, String email, String nama, String alamatRumah, String type, String noRekening, int saldo, Set<Toko> tokos, Set<Shoppingcart> shoppingcarts, Set<Transaksi> transaksis, Set<Wishlist> wishlists) {
       this.password = password;
       this.email = email;
       this.nama = nama;
       this.alamatRumah = alamatRumah;
       this.type = type;
       this.noRekening = noRekening;
       this.saldo = saldo;
       this.tokos = tokos;
       this.shoppingcarts = shoppingcarts;
       this.transaksis = transaksis;
       this.wishlists = wishlists;
    }
   
    public Integer getIdPengguna() {
        return this.idPengguna;
    }
    
    public void setIdPengguna(Integer idPengguna) {
        this.idPengguna = idPengguna;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getNama() {
        return this.nama;
    }
    
    public void setNama(String nama) {
        this.nama = nama;
    }
    public String getAlamatRumah() {
        return this.alamatRumah;
    }
    
    public void setAlamatRumah(String alamatRumah) {
        this.alamatRumah = alamatRumah;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
    public String getNoRekening() {
        return this.noRekening;
    }
    
    public void setNoRekening(String noRekening) {
        this.noRekening = noRekening;
    }
    public int getSaldo() {
        return this.saldo;
    }
    
    public void setSaldo(int saldo) {
        this.saldo = saldo;
    }
    public Set<Toko> getTokos() {
        return this.tokos;
    }
    
    public void setTokos(Set<Toko> tokos) {
        this.tokos = tokos;
    }
    public Set<Shoppingcart> getShoppingcarts() {
        return this.shoppingcarts;
    }
    
    public void setShoppingcarts(Set<Shoppingcart> shoppingcarts) {
        this.shoppingcarts = shoppingcarts;
    }
    public Set<Transaksi> getTransaksis() {
        return this.transaksis;
    }
    
    public void setTransaksis(Set<Transaksi> transaksis) {
        this.transaksis = transaksis;
    }
    public Set<Wishlist> getWishlists() {
        return this.wishlists;
    }
    
    public void setWishlists(Set<Wishlist> wishlists) {
        this.wishlists = wishlists;
    }




}


