package model;
// Generated Mar 7, 2018 11:31:33 AM by Hibernate Tools 4.3.1



/**
 * Shoppingcartentry generated by hbm2java
 */
public class Shoppingcartentry  implements java.io.Serializable {


     private ShoppingcartentryId id;
     private Barang barang;
     private Shoppingcart shoppingcart;
     private int qty;

    public Shoppingcartentry() {
    }

    public Shoppingcartentry(ShoppingcartentryId id, Barang barang, Shoppingcart shoppingcart, int qty) {
       this.id = id;
       this.barang = barang;
       this.shoppingcart = shoppingcart;
       this.qty = qty;
    }
   
    public ShoppingcartentryId getId() {
        return this.id;
    }
    
    public void setId(ShoppingcartentryId id) {
        this.id = id;
    }
    public Barang getBarang() {
        return this.barang;
    }
    
    public void setBarang(Barang barang) {
        this.barang = barang;
    }
    public Shoppingcart getShoppingcart() {
        return this.shoppingcart;
    }
    
    public void setShoppingcart(Shoppingcart shoppingcart) {
        this.shoppingcart = shoppingcart;
    }
    public int getQty() {
        return this.qty;
    }
    
    public void setQty(int qty) {
        this.qty = qty;
    }




}


