package model;
// Generated Mar 7, 2018 11:31:33 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Toko generated by hbm2java
 */
public class Toko  implements java.io.Serializable {


     private Integer idToko;
     private Pengguna pengguna;
     private String alamatToko;
     private boolean status;
     private Set<Etalase> etalases = new HashSet<Etalase>(0);

    public Toko() {
    }

	
    public Toko(Pengguna pengguna, String alamatToko, boolean status) {
        this.pengguna = pengguna;
        this.alamatToko = alamatToko;
        this.status = status;
    }
    public Toko(Pengguna pengguna, String alamatToko, boolean status, Set<Etalase> etalases) {
       this.pengguna = pengguna;
       this.alamatToko = alamatToko;
       this.status = status;
       this.etalases = etalases;
    }
   
    public Integer getIdToko() {
        return this.idToko;
    }
    
    public void setIdToko(Integer idToko) {
        this.idToko = idToko;
    }
    public Pengguna getPengguna() {
        return this.pengguna;
    }
    
    public void setPengguna(Pengguna pengguna) {
        this.pengguna = pengguna;
    }
    public String getAlamatToko() {
        return this.alamatToko;
    }
    
    public void setAlamatToko(String alamatToko) {
        this.alamatToko = alamatToko;
    }
    public boolean isStatus() {
        return this.status;
    }
    
    public void setStatus(boolean status) {
        this.status = status;
    }
    public Set<Etalase> getEtalases() {
        return this.etalases;
    }
    
    public void setEtalases(Set<Etalase> etalases) {
        this.etalases = etalases;
    }




}


