package model;
// Generated Mar 7, 2018 11:31:33 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Transaksi generated by hbm2java
 */
public class Transaksi  implements java.io.Serializable {


     private Integer idTransaksi;
     private Pengguna pengguna;
     private Date tanggal;
     private String catatan;
     private String kurir;
     private String status;
     private String alamatPengiriman;
     private Set<Orderentry> orderentries = new HashSet<Orderentry>(0);

    public Transaksi() {
    }

	
    public Transaksi(Pengguna pengguna, Date tanggal, String catatan, String kurir, String status, String alamatPengiriman) {
        this.pengguna = pengguna;
        this.tanggal = tanggal;
        this.catatan = catatan;
        this.kurir = kurir;
        this.status = status;
        this.alamatPengiriman = alamatPengiriman;
    }
    public Transaksi(Pengguna pengguna, Date tanggal, String catatan, String kurir, String status, String alamatPengiriman, Set<Orderentry> orderentries) {
       this.pengguna = pengguna;
       this.tanggal = tanggal;
       this.catatan = catatan;
       this.kurir = kurir;
       this.status = status;
       this.alamatPengiriman = alamatPengiriman;
       this.orderentries = orderentries;
    }
   
    public Integer getIdTransaksi() {
        return this.idTransaksi;
    }
    
    public void setIdTransaksi(Integer idTransaksi) {
        this.idTransaksi = idTransaksi;
    }
    public Pengguna getPengguna() {
        return this.pengguna;
    }
    
    public void setPengguna(Pengguna pengguna) {
        this.pengguna = pengguna;
    }
    public Date getTanggal() {
        return this.tanggal;
    }
    
    public void setTanggal(Date tanggal) {
        this.tanggal = tanggal;
    }
    public String getCatatan() {
        return this.catatan;
    }
    
    public void setCatatan(String catatan) {
        this.catatan = catatan;
    }
    public String getKurir() {
        return this.kurir;
    }
    
    public void setKurir(String kurir) {
        this.kurir = kurir;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public String getAlamatPengiriman() {
        return this.alamatPengiriman;
    }
    
    public void setAlamatPengiriman(String alamatPengiriman) {
        this.alamatPengiriman = alamatPengiriman;
    }
    public Set<Orderentry> getOrderentries() {
        return this.orderentries;
    }
    
    public void setOrderentries(Set<Orderentry> orderentries) {
        this.orderentries = orderentries;
    }




}


