package model;
// Generated Feb 28, 2018 5:28:46 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Wishlist generated by hbm2java
 */
public class Wishlist  implements java.io.Serializable {


     private Integer idWishlist;
     private Pengguna pengguna;
     private Set<Wishlistentry> wishlistentries = new HashSet<Wishlistentry>(0);

    public Wishlist() {
    }

	
    public Wishlist(Pengguna pengguna) {
        this.pengguna = pengguna;
    }
    public Wishlist(Pengguna pengguna, Set<Wishlistentry> wishlistentries) {
       this.pengguna = pengguna;
       this.wishlistentries = wishlistentries;
    }
   
    public Integer getIdWishlist() {
        return this.idWishlist;
    }
    
    public void setIdWishlist(Integer idWishlist) {
        this.idWishlist = idWishlist;
    }
    public Pengguna getPengguna() {
        return this.pengguna;
    }
    
    public void setPengguna(Pengguna pengguna) {
        this.pengguna = pengguna;
    }
    public Set<Wishlistentry> getWishlistentries() {
        return this.wishlistentries;
    }
    
    public void setWishlistentries(Set<Wishlistentry> wishlistentries) {
        this.wishlistentries = wishlistentries;
    }




}


