package model;
// Generated Feb 28, 2018 5:28:46 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Wishlistentry generated by hbm2java
 */
public class Wishlistentry  implements java.io.Serializable {


     private WishlistentryId id;
     private Barang barang;
     private Wishlist wishlist;
     private Date tanggalEntry;

    public Wishlistentry() {
    }

    public Wishlistentry(WishlistentryId id, Barang barang, Wishlist wishlist, Date tanggalEntry) {
       this.id = id;
       this.barang = barang;
       this.wishlist = wishlist;
       this.tanggalEntry = tanggalEntry;
    }
   
    public WishlistentryId getId() {
        return this.id;
    }
    
    public void setId(WishlistentryId id) {
        this.id = id;
    }
    public Barang getBarang() {
        return this.barang;
    }
    
    public void setBarang(Barang barang) {
        this.barang = barang;
    }
    public Wishlist getWishlist() {
        return this.wishlist;
    }
    
    public void setWishlist(Wishlist wishlist) {
        this.wishlist = wishlist;
    }
    public Date getTanggalEntry() {
        return this.tanggalEntry;
    }
    
    public void setTanggalEntry(Date tanggalEntry) {
        this.tanggalEntry = tanggalEntry;
    }




}


